---
changelog_user: rtib
changelog_project: puppet-cassandra
mock_with: ':rspec'
.travis.yml:
  user: trepasi
  litmus_sets:
    - set: debian
      collection: puppet5
      commands:
      - 'echo "deb [trusted=yes] http://www.apache.org/dist/cassandra/debian 311x main" > /etc/apt/sources.list.d/cassandra.sources.list'
      - 'apt-get update'
      - 'apt-get install wget openjdk-8-jdk -y'
    - set: debian
      commands:
      - 'echo "deb [trusted=yes] http://www.apache.org/dist/cassandra/debian 311x main" > /etc/apt/sources.list.d/cassandra.sources.list'
      - 'apt-get update'
      - 'apt-get install wget openjdk-8-jdk -y'
    - set: centos
      collection: puppet5
      commands:
      - 'echo -e "[cassandra]\nname=Apache Cassandra\nbaseurl=https://www.apache.org/dist/cassandra/redhat/311x/\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://www.apache.org/dist/cassandra/KEYS\n" > /etc/yum.repos.d/cassandra.repo'
      - 'yum install -y java-1.8.0-openjdk'
    - set: centos
      commands:
      - 'echo -e "[cassandra]\nname=Apache Cassandra\nbaseurl=https://www.apache.org/dist/cassandra/redhat/311x/\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://www.apache.org/dist/cassandra/KEYS\n" > /etc/yum.repos.d/cassandra.repo'
      - 'yum install -y java-1.8.0-openjdk'
Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: rspec-retry
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
