---
changelog_user: rtib
changelog_project: puppet-cassandra
mock_with: ':rspec'
use_litmus: true
Rakefile:
  extras:
    - |
      Blacksmith::RakeTask.new do |t|
        t.build = false
        t.tag_message_pattern = "Release v%s"
      end
Gemfile:
  required:
    ':development':
      - gem: rspec-retry
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
