---
changelog_user: rtib
changelog_project: puppet-cassandra
mock_with: ':rspec'
use_litmus: true
.travis.yml:
  user: trepasi
  secure: oBs3i4UDUUH8q3aA6W3VywKz0bp/MGO2hwHvZ/pIIbKY6KyTBaV2jHSUgeBwSxkhI4EfmvkE6HDKn2oRrr5nft9ZGjnWUyRWbK6KMSRrS98MH4Ld3uCX6zMK5yCJpB6MX1xCm0jfnb4c2NJVgBrBaJFrrSYG0Jj+YILGYcomUmM4+yfF6JdtqVefRV2YHKxrOpTh8WUr9OJRzo7JwMdkWUP67orfz7/KGkqYc58INKK4qAp70n/G8qEo5YbCdTshhSbBjaXqBMb4T2VeCpJTbbvn8ZpeXF9FlHmASs+Bp08AFC/BIX19gjgPPpqqZ6hfPWZ+u6OfWIMy46qLdDwQv9tbEdRQIydl5He429AQM8CapRT52sjDg0OaUi9B2m3JFnPjxZq+qiuVRfDIjORdxB6+Xrxl3bky+laWPgbfEidTgHr2xuyGZhPEmhBEHmSPEocodsRjRP+inYfbaU+Qzsk4TXn6o8M/oDvMK+yPlSrDwOy6GYlU+Ba66FiS7cda6NErAc8z+D6blLhyGUeQ78ZW7X+EthX916MTZImvm5rFSULt82cvJe5PFaqzWRPW7mUukYLC9vgW1ldJaTLeH3YS5rfWm/EDztT+72mdo2ltOQKuqlv1ocuEUYVNk3NL/5M+F9AxlnuEU8Vnf1+YwhATCSS+YQDo8PKu/LcRjsM=
  litmus:
    provision_list:
      - travis_deb_c21
      - travis_deb_c22
      - travis_deb_c30
      - travis_deb_c311
      - travis_deb_c40
      - ---travis_el
  allow_failures:
    - env: PLATFORMS=travis_deb_v4_puppet5
    - env: PLATFORMS=travis_deb_v4_puppet6
Rakefile:
  extras:
    - |
      Blacksmith::RakeTask.new do |t|
        t.build = false
        t.tag_message_pattern = "Release v%s"
      end
Gemfile:
  required:
    ':development':
      - gem: rspec-retry
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.gitignore:
  required: &ignorepaths
      - '/.vscode/'
