---
changelog_user: rtib
changelog_project: puppet-cassandra
mock_with: ':rspec'
.travis.yml:
  user: trepasi
  # docker_sets:
  #   - set: debian
  #     collection: puppet5
  #   - set: debian
  #     collection: puppet6
  #   - set: centos
  #     collection: puppet5
  #   - set: centos
  #     collection: puppet6
Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
