---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: SET=debian PUPPET_COLLECTION=puppet5
      services: docker
      sudo: required
      bundler_args: --with system_tests
      rvm: 2.5.3
      stage: acceptance
      before_script:
      - bundler exec rake 'litmus:provision_list[debian]'
      - bundler exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundler exec rake 'litmus:install_agent[puppet5]'
      - bundler exec rake litmus:install_module
      script:
      - bundler exec rake litmus:acceptance:parallel
    -
      env: SET=debian PUPPET_COLLECTION=puppet6
      services: docker
      sudo: required
      bundler_args: --with system_tests
      rvm: 2.5.3
      stage: acceptance
      before_script:
      - bundler exec rake 'litmus:provision_list[debian]'
      - bundler exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundler exec rake 'litmus:install_agent[puppet6]'
      - bundler exec rake litmus:install_module
      script:
      - bundler exec rake litmus:acceptance:parallel
    -
      env: SET=centos PUPPET_COLLECTION=puppet5
      services: docker
      sudo: required
      bundler_args: --with system_tests
      rvm: 2.5.3
      stage: acceptance
      before_script:
      - bundler exec rake 'litmus:provision_list[centos]'
      - bundler exec rake 'litmus:install_agent[puppet5]'
      - bundler exec rake litmus:install_module
      script:
      - bundler exec rake litmus:acceptance:parallel
    -
      env: SET=centos PUPPET_COLLECTION=puppet6
      services: docker
      sudo: required
      bundler_args: --with system_tests
      rvm: 2.5.3
      stage: acceptance
      before_script:
      - bundler exec rake 'litmus:provision_list[centos]'
      - bundler exec rake 'litmus:install_agent[puppet6]'
      - bundler exec rake litmus:install_module
      script:
      - bundler exec rake litmus:acceptance:parallel
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
