---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: SET=debian PUPPET_COLLECTION=puppet5
      services: docker
      sudo: required
      bundler_args: --with system_tests
      rvm: 2.5.3
      stage: acceptance
      before_script:
      - bundler exec rake 'litmus:provision_list[debian]'
      - bundler exec bolt command run 'echo "deb [trusted=yes] http://www.apache.org/dist/cassandra/debian 311x main" > /etc/apt/sources.list.d/cassandra.sources.list' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundler exec bolt command run 'apt-get update' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundler exec bolt command run 'apt-get install iproute2 wget openjdk-8-jdk -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundler exec rake 'litmus:install_agent[puppet5]'
      - bundler exec rake litmus:install_module
      script:
      - bundler exec rake litmus:acceptance:parallel
    -
      env: SET=debian PUPPET_COLLECTION=puppet6
      services: docker
      sudo: required
      bundler_args: --with system_tests
      rvm: 2.5.3
      stage: acceptance
      before_script:
      - bundler exec rake 'litmus:provision_list[debian]'
      - bundler exec bolt command run 'echo "deb [trusted=yes] http://www.apache.org/dist/cassandra/debian 311x main" > /etc/apt/sources.list.d/cassandra.sources.list' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundler exec bolt command run 'apt-get update' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundler exec bolt command run 'apt-get install iproute2 wget openjdk-8-jdk -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundler exec rake 'litmus:install_agent[puppet6]'
      - bundler exec rake litmus:install_module
      script:
      - bundler exec rake litmus:acceptance:parallel
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="5.5.14" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="6.0.9" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: trepasi
  password:
    secure: "oBs3i4UDUUH8q3aA6W3VywKz0bp/MGO2hwHvZ/pIIbKY6KyTBaV2jHSUgeBwSxkhI4EfmvkE6HDKn2oRrr5nft9ZGjnWUyRWbK6KMSRrS98MH4Ld3uCX6zMK5yCJpB6MX1xCm0jfnb4c2NJVgBrBaJFrrSYG0Jj+YILGYcomUmM4+yfF6JdtqVefRV2YHKxrOpTh8WUr9OJRzo7JwMdkWUP67orfz7/KGkqYc58INKK4qAp70n/G8qEo5YbCdTshhSbBjaXqBMb4T2VeCpJTbbvn8ZpeXF9FlHmASs+Bp08AFC/BIX19gjgPPpqqZ6hfPWZ+u6OfWIMy46qLdDwQv9tbEdRQIydl5He429AQM8CapRT52sjDg0OaUi9B2m3JFnPjxZq+qiuVRfDIjORdxB6+Xrxl3bky+laWPgbfEidTgHr2xuyGZhPEmhBEHmSPEocodsRjRP+inYfbaU+Qzsk4TXn6o8M/oDvMK+yPlSrDwOy6GYlU+Ba66FiS7cda6NErAc8z+D6blLhyGUeQ78ZW7X+EthX916MTZImvm5rFSULt82cvJe5PFaqzWRPW7mUukYLC9vgW1ldJaTLeH3YS5rfWm/EDztT+72mdo2ltOQKuqlv1ocuEUYVNk3NL/5M+F9AxlnuEU8Vnf1+YwhATCSS+YQDo8PKu/LcRjsM="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
